
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 15 16:48:53 BRST 2015
//----------------------------------------------------

package sintatico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ORACULOINI = 2;
  public static final int ATRIBUICAO = 9;
  public static final int SMITH = 4;
  public static final int EOF = 0;
  public static final int MULTIPLICACAO = 8;
  public static final int SEPARADOR = 5;
  public static final int NUMERO = 6;
  public static final int error = 1;
  public static final int ORACULOFIM = 3;
  public static final int VARIAVEL = 7;
}

