package tradutor;

public enum Matrix {
	CIN, COUT, IF, WHILE, FOR, MAIN, ELSE, ORACULO,
    BOOL, FLOAT, VARIAVEL, INT, CHAR,
    ATRIBUICAO, NUMERO, ERROR, LITERAL, MAIOR,
    MENOR, IGUAL, DIFERENTE, MAIORIGUAL, MENORIGUAL, 
    MAIS, MENOS, MULT, DIV, COMENTARIO, 
    ABREPARENTESES, FECHAPARENTESES, ABRECOLCHETES, 
    FECHACOLCHETES, PONTOEVIRGULA, E, OU, 
}
